apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.26
        env:
          - name: MYSQL_ROOT_PASSWORD #루트 PW
            value: root
          - name: MYSQL_DATABASE #사용할 DB명
            value: apple
        ports:
        - containerPort: 3306
          protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: vol_mysql
      volumes: 
      - name: vol_mysql
        hostPath: 
          type: Directory
          path: /workspace/mysql
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysql
  name: mysql
  namespace: mysql
spec:
  type: NodePort #ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30036
    
#  externalIPs:
#    - 192.168.0.33
  selector:
    name: mysql
